# Generated by Django 5.1.1 on 2024-09-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.URLField(),
        ),
    ]
