# Generated by Django 5.1.1 on 2024-09-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_alter_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.FloatField(),
        ),
    ]
